export const KOREAN_PRODUCTS = "Korean Products"
export const KOREAN = "Korean products"
export const CHINESE = "Chinese products"
export const JAPANESE = "Japanese products"
export const CATALOG = "CATALOG"